In [3]:
import pandas as pd
import numpy as np

df  =pd.read_csv("preprocessed_train.csv", low_memory=False)
df.dropna();
#df = df.head(30000)
reviews = df.text.values;
#print(len(reviews));

#reviews = np.array2string(reviews)
labels = df.label.values;
review_str = [str(i) for i in reviews]
#print(reviews)
df.drop(0,axis = 0)
#print(type(reviews))
#reviews_tokens = [review.split() for review in review_str];

        Unnamed: 0  label                                               text
1                1      2  realli fast polit definit recommend also clean...
2                2      2  place alway amaz friendli staff great deal pro...
3                3      1  wine class friday night cool spot downstair qu...
4                4      1  round think place may potenti coupl thing tri ...
5                5      0  romant tryst planet hollywood poker room end w...
6                6      2  got color haircut final month look right styli...
7                7      0  never go place nearli empti pm sat way rear vi...
8                8      2  come year np bought staff alway super nice hel...
9                9      0  war ich mit kollegen mittag im hotz essen tage...
10              10      2  star take recommend dine liquor licenc definit...
11              11      1  nachdem wir jetzt da dritt mal vor der standen...
12              12      2  hand best polish boy sandwich cleveland dog sp...
13              13      2  oh fuzzi begin familiar tobi keith song love b...
14              14      2  tri mani cupcak magnolia prari girl swirl cupc...
15              15      1  put irish pub walmart get get wrong love idea ...
16              16      2  amaz pho ! ! ! almost drink broth straw lol ve...
17              17      1  la eiffel tower en la vega posta es eso posibl...
18              18      2  love shop best retro dress vega girl work tota...
19              19      2  definit sexi show ! surprisingli funni boyfrie...
20              20      0  someth must gone horribl wrong sinc place last...
21              21      2  happi find silk found nicol profession friendl...
22              22      2  good get qdoba serious qdoba good tast like qd...
23              23      2  anoth one favorit spot place awesom pregam blu...
24              24      2  count charleston top notch food servic ambienc...
25              25      2    amaz place ! went massag relax staff profession
26              26      2  man oh man place fuck bomb pastor asada taco d...
27              27      1  great food big portion excel custom servic car...
28              28      2  son iphon screen bust fix less hour also otter...
29              29      1  ye space cozi comfi food le club chass et pech...
30              30      0  think yelp quit nice place allow one star mini...
...            ...    ...                                                ...
399970      399971      0  came pm tuesday theyr suppos open dont go unpr...
399971      399972      2  pizza place delici ! daughter love big rush ac...
399972      399973      2  love place ! wait row half hour definit worth ...
399973      399974      2  walk place day week sinc novemb th today janua...
399974      399975      0  usual write star moira deserv one boyfriend we...
399975      399976      1  mediocr food overpr buffet come sushi californ...
399976      399977      1  food fantast though pricier side brunch good s...
399977      399978      0  servic ok c food quick arriv wait minut order ...
399978      399979      0  la vega past weekend attend mountain west conf...
399979      399980      2  whatev need done subaru guy reliabl explain ev...
399980      399981      2  fantast experi room inde whole hotel clean fre...
399981      399982      2  well first offici verizon wireless store servi...
399982      399983      1  got vanilla spice oatmeal like sliver fruit as...
399983      399984      2  place delight food eleg tast afford overal gre...
399984      399985      2  stay sever time manag staff polit help room al...
399985      399986      2  great chines food great place take friend bad ...
399986      399987      2  never forev continu come back ! ! alli gave am...
399987      399988      1  perfectli adequ gyro place small clean enough ...
399988      399989      2  use mbv least nine year fix volvo alway manag ...
399989      399990      0  bother come back year made nine guest wait fou...
399990      399991      2  happier th wine first introduc restaur year ag...
399991      399992      2  kasade fantast hair stylist best found west co...
399992      399993      1  decid grab food fish chip thought place get bu...
399993      399994      1  hot dog inch great ! frozen hot chocol desert ...
399994      399995      2  never use move compani prior famili mover expr...
399995      399996      2  went first time got kelsey dye cut hair decid ...
399996      399997      2  first experi true food kitchen trip scottsdal ...
399997      399998      2  must one talk second hand bike place countri e...
399998      399999      2  undeni best bang buck citi buck get much food ...
399999      400000      0  order hamburg order well done waitress confirm...

[399999 rows x 3 columns]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(review_str, labels, test_size=0.10, random_state=None)

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDClassifier
from sklearn import svm
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from sklearn.naive_bayes import MultinomialNB

In [11]:
text_clf = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB()),
                    ])
text_clf = text_clf.fit(X_train, y_train)

/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):

In [13]:
predicted = text_clf.predict(X_test)
np.mean(predicted == y_test)

/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):

0.776325

In [17]:
from sklearn.model_selection import GridSearchCV
parameters = {'vect__ngram_range': [(1, 1), (1, 2)],
                  'tfidf__use_idf': (True, False),
                  'clf__alpha': (1e-2, 1e-3),
                 }
gs_clf = GridSearchCV(text_clf, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(X_train, y_train)
gs_clf.best_score_
gs_clf.best_params_

/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
/Users/kaushik/anaconda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):

{'clf__alpha': 0.01, 'tfidf__use_idf': False, 'vect__ngram_range': (1, 2)}